const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.DragnDrop,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.HTMLElement,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.Touch.Cnds.OnHoldGestureObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Audio.Acts.SetSilent
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Collider: 0},
	{ScrollTo: 0},
	{Pin: 0},
	{DragDrop: 0},
	{Pathfinding: 0},
	{Jugador: 0},
	{Oconomsn: 0},
	{IconoBanderas: 0},
	{numero1: 0},
	{PATH: 0},
	{Touch: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Audio: 0},
	{Sprite4: 0},
	{milll: 0},
	{Sprite5: 0},
	{TITULO: 0},
	{BARRA: 0},
	{UNO: 0},
	{TWAIN: 0},
	{botonarriba: 0},
	{botonabajo: 0},
	{fondovideo: 0},
	{Sprite: 0},
	{Sprite7: 0},
	{numero2: 0},
	{DOS: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Video: 0},
	{Sprite11: 0},
	{TRES: 0},
	{numero3: 0},
	{Sprite13: 0},
	{CUATRO: 0},
	{numero4: 0},
	{CINCO: 0},
	{SpriteFont: 0},
	{numero5: 0},
	{Conclusion: 0},
	{numero6: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{BARRA2: 0},
	{Sprite16: 0},
	{HTMLElement: 0},
	{Browser: 0},
	{SpriteFont2: 0},
	{INTRO: 0},
	{Sprite6: 0},
	{Sprite18: 0},
	{mario: 0},
	{Sprite12: 0},
	{GATETE: 0},
	{Sprite17: 0},
	{leaa: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{Variable1: 0}
];

self.InstanceType = {
	Collider: class extends self.ISpriteInstance {},
	Jugador: class extends self.ISpriteInstance {},
	Oconomsn: class extends self.ISpriteInstance {},
	IconoBanderas: class extends self.ISpriteInstance {},
	numero1: class extends self.ISpriteFontInstance {},
	PATH: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	milll: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TITULO: class extends self.ISpriteFontInstance {},
	BARRA: class extends self.ISpriteFontInstance {},
	UNO: class extends self.ISpriteFontInstance {},
	TWAIN: class extends self.ISpriteInstance {},
	botonarriba: class extends self.ISpriteInstance {},
	botonabajo: class extends self.ISpriteInstance {},
	fondovideo: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	numero2: class extends self.ISpriteFontInstance {},
	DOS: class extends self.ISpriteFontInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	TRES: class extends self.ISpriteFontInstance {},
	numero3: class extends self.ISpriteFontInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	CUATRO: class extends self.ISpriteFontInstance {},
	numero4: class extends self.ISpriteFontInstance {},
	CINCO: class extends self.ISpriteFontInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	numero5: class extends self.ISpriteFontInstance {},
	Conclusion: class extends self.ISpriteFontInstance {},
	numero6: class extends self.ISpriteFontInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	BARRA2: class extends self.ISpriteFontInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	HTMLElement: class extends self.IHTMLElementInstance {},
	Browser: class extends self.IInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	INTRO: class extends self.ISpriteFontInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	mario: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	GATETE: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	leaa: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {}
}